### Assignment no - 20 Building & Deplyoing a Recommendation system
## PART 1- Data Processing
# Task 1:- Load and understand Dataset

In [133]:
import pandas as pd
import scipy

In [134]:
d1=pd.read_csv('books.csv')

d2=pd.read_csv('book_tags.csv')

d3=pd.read_csv('tags.csv')

In [135]:
d1.shape

(10000, 23)

In [136]:
d2.head()

   goodreads_book_id  tag_id   count
0                  1   30574  167697
1                  1   11305   37174
2                  1   11557   34173
3                  1    8717   12986
4                  1   33114   12716

In [137]:
d2.shape

(999912, 3)

In [138]:
d3.shape

(34252, 2)

In [139]:
d1.head()

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...

In [140]:
d2.head(3)

   goodreads_book_id  tag_id   count
0                  1   30574  167697
1                  1   11305   37174
2                  1   11557   34173

In [141]:
d3.head(3)

   tag_id tag_name
0       0        -
1       1     --1-
2       2    --10-

In [142]:
# Merge d2 with d3 to get readable tag names.

merged_tags = d2.merge(d3,on='tag_id',how='left')

merged_tags.head()

   goodreads_book_id  tag_id   count           tag_name
0                  1   30574  167697            to-read
1                  1   11305   37174            fantasy
2                  1   11557   34173          favorites
3                  1    8717   12986  currently-reading
4                  1   33114   12716        young-adult

In [143]:
# Collect Tags for Each Book

d2_grouped = (merged_tags.groupby('goodreads_book_id')['tag_name'].apply(lambda x: ' '.join(x.astype(str))).reset_index())

In [144]:
d2_grouped.head()

   goodreads_book_id                                           tag_name
0                  1  to-read fantasy favorites currently-reading yo...
1                  2  to-read currently-reading fantasy favorites ch...
2                  3  to-read favorites fantasy currently-reading yo...
3                  5  favorites fantasy currently-reading young-adul...
4                  6  fantasy young-adult fiction harry-potter owned...

In [145]:
d1.columns.tolist()

['book_id',
 'goodreads_book_id',
 'best_book_id',
 'work_id',
 'books_count',
 'isbn',
 'isbn13',
 'authors',
 'original_publication_year',
 'original_title',
 'title',
 'language_code',
 'average_rating',
 'ratings_count',
 'work_ratings_count',
 'work_text_reviews_count',
 'ratings_1',
 'ratings_2',
 'ratings_3',
 'ratings_4',
 'ratings_5',
 'image_url',
 'small_image_url']

In [146]:
# Merge tags with Books

books = d1.merge(d2_grouped,on = 'goodreads_book_id',how = 'left')

In [147]:
books.head()

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,tag_name
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,favorites currently-reading young-adult fictio...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,...,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,to-read favorites fantasy currently-reading yo...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...,young-adult fantasy favorites vampires ya fict...
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...,classics favorites to-read classic historical-...
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...,classics favorites fiction classic books-i-own...

In [148]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   book_id                    10000 non-null  int64
 1   goodreads_book_id          10000 non-null  int64
 2   best_book_id               10000 non-null  int64
 3   work_id                    10000 non-null  int64
 4   books_count                10000 non-null  int64
 5   isbn                       9300 non-null   object
 6   isbn13                     9415 non-null   float64
 7   authors                    10000 non-null  object
 8   original_publication_year  9979 non-null   float64
 9   original_title             9415 non-null   object
 10  title                      10000 non-null  object
 11  language_code              8916 non-null   object
 12  average_rating             10000 non-null  float64
 13  ratings_count              10000 non-null  int64
 14  work_ratings_count         10000 non-null  int64
 15  work_text_reviews_count    10000 non-null  int64
 16  ratings_1                  10000 non-null  int64
 17  ratings_2                  10000 non-null  int64
 18  ratings_3                  10000 non-null  int64
 19  ratings_4                  10000 non-null  int64
 20  ratings_5                  10000 non-null  int64
 21  image_url                  10000 non-null  object
 22  small_image_url            10000 non-null  object
 23  tag_name                   10000 non-null  object
dtypes: float64(3), int64(13), object(8)
memory usage: 1.8+ MB

In [149]:
# Handling missing values

cols = ['title','authors','original_title','tag_name']
books = books[cols]

In [150]:
books[cols] = books[cols].fillna('')

In [151]:
books[cols].isnull().sum()

title             0
authors           0
original_title    0
tag_name          0
dtype: int64

In [152]:
books[cols].duplicated().sum()

np.int64(0)

In [153]:
books.head()

,title,authors,original_title,tag_name
0,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,The Hunger Games,favorites currently-reading young-adult fictio...
1,Harry Potter and the Sorcerer's Stone (Harry P...,"J.K. Rowling, Mary GrandPré",Harry Potter and the Philosopher's Stone,to-read favorites fantasy currently-reading yo...
2,"Twilight (Twilight, #1)",Stephenie Meyer,Twilight,young-adult fantasy favorites vampires ya fict...
3,To Kill a Mockingbird,Harper Lee,To Kill a Mockingbird,classics favorites to-read classic historical-...
4,The Great Gatsby,F. Scott Fitzgerald,The Great Gatsby,classics favorites fiction classic books-i-own...

In [154]:
books['text']=(books['title'].fillna('')+' '+books['authors'].fillna('')+' '+books['original_title'].fillna('')+' '+books['tag_name'].fillna('')).str.lower()

## Task 2:- Text preprocessing for Recommendation

In [155]:
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to C:\Users\Deepak
[nltk_data]     Shukla\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [156]:
# cleaning function
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9]',' ',text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return ' '.join(words)

In [157]:
# Apply
books['clean_text'] = books['text'].apply(clean_text)

## PART 2- Text Vectorization
# Task 3:- Vectorization using TF-IDF

In [158]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [159]:
tfidf = TfidfVectorizer(max_features=5000,stop_words='english',ngram_range=(1,2))

In [160]:
tfidf_matrix = tfidf.fit_transform(books['clean_text'])
print(tfidf_matrix.shape)

(10000, 5000)

# Task 4:- Similarity Coputation

In [161]:
from sklearn.metrics.pairwise import cosine_similarity

In [162]:
similarity = cosine_similarity(tfidf_matrix)
print(similarity.shape)

(10000, 10000)

# Why cosine similarity?
- Works well on Sparse TF-IDF vectors.
- Measures similarity by comparing vector directions rather than document length.
- Produces similarity scores between 0 and 1.
- Widely used in content-based recommendation system.

## PART 3- Recommendation Logic
# Task 5:- Build Recommendation Function

In [163]:
def recommend(book_name, top_n=10):
    
    book_name = book_name.lower().strip()

    matches = books[books['title'].str.lower().str.contains(book_name, na=False)]
    if matches.empty:
        return 'Book not Found'

    idx = matches.index[0]

    sim_scores = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()

    top_indices = sim_scores.argsort()[-top_n-1:-1][::-1]
    recommendations = books.iloc[top_indices][['title','authors',]]
    return recommendations

In [164]:
recommend("the hobbit")

,title,authors
188,"The Lord of the Rings (The Lord of the Rings, ...",J.R.R. Tolkien
154,"The Two Towers (The Lord of the Rings, #2)",J.R.R. Tolkien
610,The Silmarillion (Middle-Earth Universe),"J.R.R. Tolkien, Christopher Tolkien, Ted Nasmith"
2308,The Children of Húrin,"J.R.R. Tolkien, Christopher Tolkien, Alan Lee"
18,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. Tolkien
160,"The Return of the King (The Lord of the Rings,...",J.R.R. Tolkien
963,J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...,J.R.R. Tolkien
4975,Unfinished Tales of Númenor and Middle-Earth,"J.R.R. Tolkien, Christopher Tolkien"
8271,The Complete Guide to Middle-Earth,"Robert Foster, J.R.R. Tolkien"
1128,"The History of the Hobbit, Part One: Mr. Baggins","John D. Rateliff, J.R.R. Tolkien"

## PART 4 - Simple App Interface
# Task 6:- Build UI using Streamlit

In [171]:
books_data = books[['title','authors','clean_text']]

In [172]:
import pickle
with open('books.pickle','wb') as B:
    pickle.dump(books_data,B)

In [173]:
with open('tfidf_matrix.pickle','wb') as B:
    pickle.dump(tfidf_matrix,B)